### ISSUE TITLE
Error pops up from bcolz while ingesting csv data into zipline-reloaded

### ISSUE THREAD

**Issue by Moccazio** [stefan-jansen/zipline-reloaded#109]
I was running zipline for quite a long time now and I was using csv data to ingest into zipline. Today I updated the environment and now bcolz shows an new error while trying to ingest the csv data. 

**System data**
Compiler    : Clang 11.1.0 
OS          : Darwin
Release     : 21.5.0
Machine     : x86_64
Processor   : i386
CPU cores   : 16
Architecture: 64bit

**Error**
`Traceback (most recent call last):
  File "/Users/mw/opt/anaconda3/envs/ml4t/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bundles/core.py", line 415, in ingest
    daily_bar_writer.write(())
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bcolz_daily_bars.py", line 209, in write
    return self._write_internal(it, assets)
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bcolz_daily_bars.py", line 250, in _write_internal
    columns = {
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bcolz_daily_bars.py", line 251, in <dictcomp>
    k: carray(array([], dtype=uint32_dtype))
  File "bcolz/carray_ext.pyx", line 1063, in bcolz.carray_ext.carray.__cinit__
  File "bcolz/carray_ext.pyx", line 1132, in bcolz.carray_ext.carray._create_carray
  File "/Users/mw/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/bcolz/utils.py", line 113, in to_ndarray
    if array.dtype != dtype.base:
AttributeError: 'NoneType' object has no attribute 'base'`

**Comment by RichardDale** [comment]
There appears to have been introduced with numpy v1.23

I recommend you use numpy v1.21.3 instead.

@stefan-jansen you might want to restrict this (or investigate the bug further)

**Comment by Moccazio** [comment]
> There appears to have been introduced with numpy v1.23
> 
> I recommend you use numpy v1.21.3 instead.
> 
> @stefan-jansen you might want to restrict this (or investigate the bug further)

Thank you for the fast reply. Using numpy v1.21.3 worked to fix that error while ingesting csv data into zipline.

**Comment by RichardDale** [comment]
Further to this, I'm going to raise this as a separate issue so others can find it (it's not actually related to csv data at all)

**Comment by RichardDale** [comment]
See #110

**Comment by stefan-jansen** [comment]
Fixed with latest updates; see #110.
