### ISSUE TITLE
During ingest, with numpy 1.23.0, bcolz provides cryptic error message AttributeError: 'NoneType' object has no attribute 'base'

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#110]
This appears to be related to a change within Numpy v1.23.0.

It could quite possible be a bcolz forward-compatibility bug.

Works fine in:
numpy v1.22.4
numpy v1.21.6
numpy v1.21.3

In numpy v1.23.0:

```Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\envs\zip20220704\Scripts\zipline-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\zipline\__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\zipline\data\bundles\core.py", line 415, in ingest
    daily_bar_writer.write(())
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 209, in write
    return self._write_internal(it, assets)
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 250, in _write_internal
    columns = {
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 251, in <dictcomp>
    k: carray(array([], dtype=uint32_dtype))
  File "bcolz\carray_ext.pyx", line 1063, in bcolz.carray_ext.carray.__cinit__
  File "bcolz\carray_ext.pyx", line 1132, in bcolz.carray_ext.carray._create_carray
  File "C:\Users\richa\anaconda3\envs\zip20220704\lib\site-packages\bcolz\utils.py", line 113, in to_ndarray
    if array.dtype != dtype.base:
AttributeError: 'NoneType' object has no attribute 'base'
```

**Comment by RichardDale** [comment]
Workaround during install - force install numpy 1.22.4

Here's how I install a fresh environment (as at 20220729 - this is likely a moving target):

```
conda create -y -n zip38 python=3.8
conda activate zip38
conda install -y -c conda-forge mamba
mamba install -y -c ml4t -c conda-forge -c ranaroussi pandas==1.3.5 numpy==1.22.4  zipline-reloaded pyfolio-reloaded iso3166==2.0.2
mamba install -y -c conda-forge jupyter
if not exist %HOMEPATH%\.zipline mkdir %HOMEPATH%\.zipline
if not exist %HOMEPATH%\.zipline\extension.py copy /b NUL > %HOMEPATH%\.zipline\extension.py
```

**Comment by ari62** [comment]
This thread mentions altering the bcolz library as another possible workaround:
https://exchange.ml4trading.io/t/error-during-bundle-ingestion-for-zipline/800

**Comment by stefan-jansen** [comment]
Addressed by [bcolz-zipline](https://github.com/stefan-jansen/bcolz-zipline) update (on main, and PyPI, pending release).
