### ISSUE TITLE
zipline ingest not working

### ISSUE THREAD

**Issue by Tulgas1973** [stefan-jansen/zipline-reloaded#130]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: 
Windows 10 Pro

* Python Version: 
3.9 (I also tried 3.5, 3.6, 3.7 and 3.8)

* How did you install Zipline: 
mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded
(I also tried pip and conda, but no luck).

* Python packages: `$ pip freeze` or `$ conda list`
# Name                    Version                   Build  Channel
alembic                   1.8.1              pyhd8ed1ab_0    conda-forge
bcolz-zipline             1.2.4            py39he6999da_0    ml4t
blosc                     1.21.1               h74325e0_3    conda-forge
bottleneck                1.3.5            py39h5d4886f_0    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.6.15          pyhd8ed1ab_1    conda-forge
cffi                      1.15.1           py39h0878f49_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hcbf5309_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.14.0           py39hcbf5309_0    conda-forge
conda-package-handling    1.8.1            py39hb3671d1_1    conda-forge
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
empyrical-reloaded        0.5.8                    py39_0    ml4t
greenlet                  1.1.3            py39h415ef7b_0    conda-forge
h5py                      3.7.0           nompi_py39h7fe8f52_101    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39hcbf5309_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
iso3166                   2.0.2              pyhd8ed1ab_0    conda-forge
iso4217                   1.9.20220401       pyhd8ed1ab_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
libarchive                3.5.2                hb45042f_3    conda-forge
libblas                   3.9.0           16_win64_openblas    conda-forge
libcblas                  3.9.0           16_win64_openblas    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0           16_win64_openblas    conda-forge
libmamba                  0.25.0               h81a967f_2    conda-forge
libmambapy                0.25.0           py39h4126fcf_2    conda-forge
libopenblas               0.3.21          pthreads_h02691f0_0    conda-forge
libsolv                   0.7.22               h7755175_0    conda-forge
libsqlite                 3.39.2               h8ffe710_1    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libxslt                   1.1.35               h34f844d_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
logbook                   1.5.3                    py39_0    ml4t
lru-dict                  1.1.8            py39hb82d6ee_0    conda-forge
lxml                      4.9.1            py39hb82d6ee_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.2.2              pyhd8ed1ab_0    conda-forge
mamba                     0.25.0           py39hb3d9227_2    conda-forge
markupsafe                2.1.1            py39hb82d6ee_1    conda-forge
menuinst                  1.4.19           py39hcbf5309_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.3           py39h5ea59f0_100    conda-forge
numpy                     1.23.2           py39h1a62c8c_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.2.5            py39h2e25243_0    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.7.0            py39hcbeb248_2    conda-forge
python                    3.9.0           h7840368_5_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-interface          1.6.0                      py_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
reproc                    14.2.3               h8ffe710_0    conda-forge
reproc-cpp                14.2.3               h0e60522_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1007    conda-forge
scipy                     1.9.1            py39h316f440_0    conda-forge
setuptools                59.8.0           py39hcbf5309_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.40           py39hb82d6ee_0    conda-forge
sqlite                    3.39.2               h8ffe710_1    conda-forge
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
ta-lib                    0.4.19           py39hb572761_0    ml4t
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_7    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.7.0                h0e60522_1    conda-forge
yfinance                  0.1.63                     py_0    ml4t
zipline-reloaded          2.1.1            py39he6999da_0    ml4t
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I created a new environment in Anaconda and installed zipline-reloaded. I tried first installing jupyter notebook, matplotlib, and so on, but the last times I just tried the minimum installation of zipline. It gets installed but can't get the zipline ingest command to work.

* What did you expect to happen?
After running:
zipline ingest -b quandl
I expect to retrieve the data bundle.

* What happened instead?

I get this error:

D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\__main__.py:54: UserWarning: Failed to load extension: 'C:\\Users\\jesus.VLT-NL/.zipline\\extension.py'
No module named 'zipline.data.bundles.ingester'
  load_extensions(
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\zip39\Scripts\zipline-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\data\bundles\core.py", line 415, in ingest
    daily_bar_writer.write(())
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 209, in write
    return self._write_internal(it, assets)
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 250, in _write_internal
    columns = {
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 251, in <dictcomp>
    k: carray(array([], dtype=uint32_dtype))
  File "bcolz\carray_ext.pyx", line 1063, in bcolz.carray_ext.carray.__cinit__
  File "bcolz\carray_ext.pyx", line 1132, in bcolz.carray_ext.carray._create_carray
  File "D:\ProgramData\Anaconda3\envs\zip39\lib\site-packages\bcolz\utils.py", line 113, in to_ndarray
    if array.dtype != dtype.base:
AttributeError: 'NoneType' object has no attribute 'base'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

From a newly created Anaconda environment (I use Anaconda Navigator 2.2.0):

conda create -n z39 python=3.9
conda activate zip39
conda deactivate
conda activate zip39
conda install -y -c conda-forge mamba
conda install python==3.9    # the previous command upgrades python to 3.10
mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded
mamba install iso3166==2.0.2    # if I don't do this I get some error related to TURKEY.
set QUANDL_API_KEY=<my_key>
zipline ingest -b quandl

## What steps have you taken to resolve this already?

I tried different python verisons, I tried using pip, conda, mamba, nothing works. The package seems to get installed with no issues (some times), but can't get the ingest command to work.

# Anything else?

I came across zipline while reading your book 'Machine Lerning for Algorithmic Trading' and I tohugh it would be a nice tool for developioing and tesintg strategies. I appreciate your help with this, I wasted countless hours over many days with this and I'm about to give up. I honestly don't know what I'm doing wrong. Thanks very much in advance.

Sincerely,

    Tulgas

**Comment by Tulgas1973** [comment]
Reading other issues I found the fix. 

Here it is just in case can be helpful for anyone else:

I just downgraded numpy to 1.22.4 with:

mamba install numpy==1.22.4

Thanks and sorry for not seeing it earlier!
