### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'base'" as ingesting data

### ISSUE THREAD

**Issue by wuyuhang1995** [stefan-jansen/zipline-reloaded#134]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10 
* Python Version: python 3.8
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: alembic                   1.8.1              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0    anaconda
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0    anaconda
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
attrs                     21.4.0             pyhd3eb1b0_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bcolz-zipline             1.2.4            py38he6999da_0    ml4t
beautifulsoup4            4.11.1           py38haa95532_0    anaconda
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0    anaconda
blosc                     1.21.1               h74325e0_3    conda-forge
bottleneck                1.3.5            py38hbdcd294_0    conda-forge
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.14            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py38haa244fe_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4           py38hb7941b4_0    conda-forge
debugpy                   1.5.1            py38hd77b12b_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
defusedxml                0.7.1              pyhd3eb1b0_0    anaconda
empyrical-reloaded        0.5.8                    py38_0    ml4t
entrypoints               0.4              py38haa95532_0    anaconda
exchange-calendars        3.3                      py38_0    ml4t
executing                 0.8.3              pyhd3eb1b0_0    anaconda
greenlet                  1.1.3            py38h885f38d_0    conda-forge
h5py                      3.7.0           nompi_py38h35e7eba_101    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1            py38haa95532_0    anaconda
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.15.2           py38haa95532_0
ipython                   8.3.0            py38haa95532_0    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
ipywidgets                7.6.5              pyhd3eb1b0_1    anaconda
iso3166                   2.0.2                    pypi_0    pypi
iso4217                   1.9.20220401       pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py38haa95532_1    anaconda
jinja2                    3.0.3              pyhd3eb1b0_0    anaconda
jpeg                      9e                   h2bbff1b_0    anaconda
jsonschema                4.4.0            py38haa95532_0    anaconda
jupyter                   1.0.0                    py38_7    anaconda
jupyter_client            7.2.2            py38haa95532_0    anaconda
jupyter_console           6.4.3              pyhd3eb1b0_0    anaconda
jupyter_core              4.10.0           py38haa95532_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    anaconda
korean_lunar_calendar     0.3.1              pyhd8ed1ab_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0    anaconda
libssh2                   1.10.0               h680486a_3    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libxslt                   1.1.35               h34f844d_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.8            py38h294d835_0    conda-forge
lxml                      4.9.1            py38h294d835_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.2.2              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38h294d835_1    conda-forge
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
mistune                   0.8.4           py38he774522_1000    anaconda
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h4f8af0f_0    conda-forge
more-itertools            8.12.0             pyhd3eb1b0_0    anaconda
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.13           py38haa95532_0    anaconda
nbconvert                 6.4.4            py38haa95532_0    anaconda
nbformat                  5.3.0            py38haa95532_0    anaconda
nest-asyncio              1.5.5            py38haa95532_0    anaconda
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
notebook                  6.4.11           py38haa95532_0    anaconda
numexpr                   2.8.3            py38hb80d3ca_0
numpy                     1.23.1           py38h223ccf5_0    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38hcc40339_0    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pip                       22.1.2           py38haa95532_0
prometheus_client         0.13.1             pyhd3eb1b0_0    anaconda
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
prompt_toolkit            3.0.20               hd3eb1b0_0    anaconda
psutil                    5.9.0            py38h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyluach                   2.0.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py38ha925a31_4    anaconda
pyrsistent                0.18.0           py38h196d8e1_0    anaconda
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.7.0            py38hc0e850c_2    conda-forge
python                    3.8.13               h6244533_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    anaconda
python-interface          1.6.0                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywin32                   302              py38h2bbff1b_2    anaconda
pywinpty                  2.0.2            py38h5da7b33_0    anaconda
pyzmq                     22.3.0           py38hd77b12b_2    anaconda
qt                        5.9.7            vc14h73c81de_0  [vc14]  anaconda
qtconsole                 5.3.0              pyhd3eb1b0_0    anaconda
qtpy                      2.0.1              pyhd3eb1b0_0    anaconda
quandl                    3.6.1            py38haa95532_0    anaconda
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scipy                     1.8.1            py38h4990095_2    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1    anaconda
setuptools                63.4.1           py38haa95532_0
sip                       6.5.1            py38hd77b12b_0    anaconda
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd3eb1b0_0    anaconda
sqlalchemy                1.4.13           py38h294d835_0    conda-forge
sqlite                    3.39.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
statsmodels               0.13.2           py38hbdcd294_0    conda-forge
ta-lib                    0.4.21           py38hb572761_0    ml4t
tbb                       2021.5.0             h2d74725_1    conda-forge
terminado                 0.13.1           py38haa95532_0    anaconda
testpath                  0.6.0            py38haa95532_0    anaconda
toml                      0.10.2             pyhd3eb1b0_0    anaconda
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h2bbff1b_0    anaconda
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
typing-extensions         4.1.1                hd3eb1b0_0    anaconda
typing_extensions         4.1.1              pyh06a4308_0    anaconda
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    py38_1    anaconda
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2            py38haa95532_0    anaconda
win_inet_pton             1.1.0            py38haa244fe_4    conda-forge
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4    anaconda
xz                        5.2.6                h8d14728_0    conda-forge
yfinance                  0.1.63                     py_0    ml4t
zipline-reloaded          2.2.0            py38he6999da_0    ml4t
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8cc25b3_2    anaconda
zstd                      1.5.2                h6255e5f_4    conda-forge

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

AttributeError: 'NoneType' object has no attribute 'base' as ingesting data.

# Description of Issue

* What did you expect to happen?

I try to ingest the data by running `$ zipline ingest -b quandl`
I expect to have the data ingested.

* What happened instead?

However, I get the following error:

`Traceback (most recent call last):
  File "D:\Anaconda\envs\env_zipline\Scripts\zipline-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\zipline\__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\zipline\data\bundles\core.py", line 415, in ingest
    daily_bar_writer.write(())
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 209, in write
    return self._write_internal(it, assets)
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 250, in _write_internal
    columns = {
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\zipline\data\bcolz_daily_bars.py", line 251, in <dictcomp>
    k: carray(array([], dtype=uint32_dtype))
  File "bcolz\carray_ext.pyx", line 1063, in bcolz.carray_ext.carray.__cinit__
  File "bcolz\carray_ext.pyx", line 1132, in bcolz.carray_ext.carray._create_carray
  File "D:\Anaconda\envs\env_zipline\lib\site-packages\bcolz\utils.py", line 113, in to_ndarray
    if array.dtype != dtype.base:
AttributeError: 'NoneType' object has no attribute 'base'`

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Simple run `$ zipline ingest -b quandl` in command prompt.

...

## What steps have you taken to resolve this already?

I am sorry. I have no idea which direction to go.

...

# Anything else?

Thank you!

...

Sincerely,
Yuhang

**Comment by wuyuhang1995** [comment]
The problem has been solved by following #110.
