### ISSUE TITLE
Timestamp Missing for 2022-06-20 ?

### ISSUE THREAD

**Issue by Moccazio** [stefan-jansen/zipline-reloaded#136]
Does anybody know how to fix that calender error?

`
[2022-10-01 19:35:49.828490] INFO: zipline.data.bundles.core: Ingesting iex.
[2022-10-01 19:35:49.828587] INFO: zipline.data.bundles.ingester: symbols are: ('TLT', 'EEM', 'GLD', 'QQQ', 'EFA', 'SPY', 'ACWI', 'IEF', 'DAX')
[2022-10-01 19:35:49.829531] INFO: zipline.data.bundles.ingester: writing data...
/Users/maximilian/.zipline/extension.py:54: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version.  Use a timezone-aware object instead.
  filter_cb=lambda df: df[[cal.is_session(dt) for dt in df.index]]
[?25h
Traceback (most recent call last):
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bundles/core.py", line 443, in ingest
    bundle.ingest(
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bundles/ingester.py", line 421, in __call__
    daily_bar_writer.write(self._read_and_convert(calendar, show_progress), show_progress=show_progress)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bcolz_daily_bars.py", line 209, in write
    return self._write_internal(it, assets)
  File "/Users/maximilian/opt/anaconda3/envs/ml4t/lib/python3.8/site-packages/zipline/data/bcolz_daily_bars.py", line 308, in _write_internal
    assert len(table) == len(asset_sessions), (
AssertionError: Got 693 rows for daily bars table with first day=2020-01-02, last day=2022-09-30, expected 694 rows.
Missing sessions: [Timestamp('2022-06-20 00:00:00+0000', tz='UTC')]
Extra sessions: []
[?25h`

**Comment by anandsork** [comment]
Hi,
  Can you please let me know, how did you resolve this?
