### ISSUE TITLE
Error ingesting quandl data: AttributeError: 'Connection' object has no attribute 'connect'

### ISSUE THREAD

**Issue by Coreyeck** [stefan-jansen/zipline-reloaded#163]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: MacOSX 12.6.2
* Python Version: 3.8.15
* Python Bitness: 64
* How did you install Zipline: conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded
* Python packages: 
* # packages in environment at ~/opt/anaconda3/envs/zipline:
#
# Name                    Version                   Build  Channel
alembic                   1.9.1              pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38hef030d1_3    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcolz-zipline             1.2.6            py38h6595a18_0    ml4t
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.2               hebb52c4_0    conda-forge
bottleneck                1.3.6            py38hbd87e4b_0    conda-forge
brotlipy                  0.7.0           py38hef030d1_1005    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38hb368cf1_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
cryptography              39.0.0           py38h4257468_0    conda-forge
debugpy                   1.6.6            py38h4cd09af_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
empyrical-reloaded        0.5.8                    py38_0    ml4t
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exchange-calendars        3.3                      py38_0    ml4t
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
greenlet                  2.0.1            py38h4cd09af_0    conda-forge
h5py                      3.8.0           nompi_py38h2bdbf1d_100    conda-forge
hdf5                      1.12.2          nompi_h48135f9_101    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_resources       5.10.2             pyhd8ed1ab_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.20.2             pyh736e0ef_0    conda-forge
ipython                   8.9.0              pyhd1c38e8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
iso3166                   2.1.1              pyhd8ed1ab_0    conda-forge
iso4217                   1.9.20220401       pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.5            py38h50d1736_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.1.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
korean_lunar_calendar     0.3.1              pyhd8ed1ab_0    conda-forge
krb5                      1.20.1               h049b76e_0    conda-forge
libaec                    1.0.6                hf0c8a7f_1    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcurl                   7.87.0               h6df9250_0    conda-forge
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           11_3_0_h97931a8_27    conda-forge
libgfortran5              11.3.0              h082f757_27    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libnghttp2                1.51.0               he2ab024_0    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libxml2                   2.10.3               hb9e07b5_0    conda-forge
libxslt                   1.1.37               h5d22bc9_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               15.0.7               h61d9ccf_0    conda-forge
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.8            py38hef030d1_1    conda-forge
lxml                      4.9.2            py38h64add32_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
mako                      1.2.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2            py38hef030d1_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
nb_conda                  2.2.1                    unix_6    conda-forge
nb_conda_kernels          2.3.1            py38h50d1736_2    conda-forge
nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.3            py38hec72209_1    conda-forge
numpy                     1.24.1           py38hc2f29e8_0    conda-forge
openssl                   3.0.7                hfd90126_2    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py38h743cdd8_0  
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandoc                    2.19.2               h694c41f_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.4            py38hef030d1_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyluach                   2.0.2              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py38hef030d1_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.7.0            py38h9f12aa8_3    conda-forge
python                    3.8.15          hf9b03c3_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-interface          1.6.0                      py_0    conda-forge
python-json-logger        2.0.4              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38hef030d1_5    conda-forge
pyzmq                     25.0.0           py38h0b711fd_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
scipy                     1.10.0           py38hfb8b963_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h225ccf5_2    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.0            py38hef030d1_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5           py38hbd87e4b_2    conda-forge
ta-lib                    0.4.25           py38h2fabc88_0    ml4t
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38hef030d1_1    conda-forge
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
traitlets                 5.8.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.0              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yfinance                  0.1.63                     py_0    ml4t
zeromq                    4.3.4                he49afe7_1    conda-forge
zipline-reloaded          2.3              py38h15fa1a4_0    ml4t
zipp                      3.12.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Attempted to ingest Quandl data by executing the following command:
zipline ingest -b quandl
* What happened instead?
Received the following error: 
(zipline) coreyeck@iMac ~ % zipline ingest -b quandl
[2023-01-28 17:37:23.482760] INFO: zipline.data.bundles.core: Ingesting quandl.
[2023-01-28 17:37:23.482903] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
Downloading WIKI Prices table from Quandl  [####################################]  100%          
[2023-01-28 17:37:41.157807] INFO: zipline.data.bundles.quandl: Parsing raw data.
[2023-01-28 17:38:06.067698] INFO: zipline.data.bundles.quandl: Generating asset metadata.
Traceback (most recent call last):
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/data/bundles/core.py", line 445, in ingest
    bundle.ingest(
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/data/bundles/quandl.py", line 193, in quandl_bundle
    asset_db_writer.write(equities=asset_metadata, exchanges=exchanges)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/assets/asset_writer.py", line 816, in write
    self._real_write(
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/assets/asset_writer.py", line 492, in _real_write
    self.init_db(conn)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/assets/asset_writer.py", line 917, in init_db
    tables_already_exist = self._all_tables_present(txn)
  File "/Users/coreyeck/opt/anaconda3/envs/zipline/lib/python3.8/site-packages/zipline/assets/asset_writer.py", line 893, in _all_tables_present
    conn = txn.connect()
AttributeError: 'Connection' object has no attribute 'connect'

## What steps have you taken to resolve this already?

Searched the web but can find nothing on this particular error as it relates to trying to ingest quandl data.

# Anything else?

...

Sincerely,
Corey

**Comment by Coreyeck** [comment]
Found the solution to this in a prior issue. Apologies, this is a dupe.
