### ISSUE TITLE
installing zipline with wheel breaks existing talib package

### ISSUE THREAD

**Issue by sceamms** [stefan-jansen/zipline-reloaded#165]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`) : macos ventura 13.2
* Python Version: `$ python --version` python 3.9.16
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) use pip install /Volumes//Download/zipline_reloaded-2.4.0b1-cp39-cp39-macosx_11_0_arm64.whl
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

I had talib issue initially, I cannot import talib for some reasons. then create a new environment install talib again, the import succeeded and everything seems normal. then I install zipline....whl as above.. the install seems ok. but afterwards I can no longer import talib again. it gives following error. so I concluded that install the zipline wheel breaks the existing talib package which was working. see error message below

import talib
[autoreload of numpy.core.multiarray failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/multiarray.py", line 16, in <module>
    from ._multiarray_umath import (
ImportError: cannot import name '_fastCopyAndTranspose' from 'numpy.core._multiarray_umath' (/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so)
]
[autoreload of numpy.core.numeric failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/numeric.py", line 10, in <module>
    from .multiarray import (
ImportError: cannot import name '_fastCopyAndTranspose' from 'numpy.core.multiarray' (/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/multiarray.py)
]
[autoreload of numpy.linalg.linalg failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 85, in <module>
    _linalg_error_extobj = _determine_error_states()
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 78, in _determine_error_states
    with errstate(invalid='call', over='ignore',
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/_ufunc_config.py", line 433, in __enter__
ValueError: Only callable can be used as callback
]
[autoreload of numpy.matrixlib failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/matrixlib/__init__.py", line 6, in <module>
    __all__ = defmatrix.__all__
NameError: name 'defmatrix' is not defined
]
[autoreload of numpy.lib failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/lib/__init__.py", line 44, in <module>
    __all__ += type_check.__all__
NameError: name 'type_check' is not defined
]
[autoreload of numpy failed: Traceback (most recent call last):
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/__init__.py", line 191, in <module>
    core.numerictypes.typeDict,
  File "/Users/wangshu/opt/anaconda3/envs/bt39_talib/lib/python3.9/site-packages/numpy/core/__init__.py", line 161, in __getattr__
    raise AttributeError(f"Module {__name__!r} has no attribute {name!r}")
AttributeError: Module 'numpy.core' has no attribute 'numerictypes'
]

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. create new python environment with python version 3.9.16
2. install talib
3. install zipline as below
4. import talib, then error will appears
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by sceamms** [comment]
after reinstalling several times, it works somehow.. so I close it for now.

**Comment by sceamms** [comment]
after reinstalling several times, it works somehow.. so I close it for now.
