### ISSUE TITLE
Error when ingesting quandl data

### ISSUE THREAD

**Issue by tankyk** [stefan-jansen/zipline-reloaded#197]
Dear Zipline Maintainers,

I am trying to get started with zipline-reloaded. I installed zipline 2.4 without issue using:
> conda install -c conda-forge zipline-reloaded

However, I hit an error when I tried to ingest the quandl data bundle using:
> zipline ingest -b quandl

The error message is:
[2023-06-18T23:17:24+0800-INFO][zipline.data.bundles.core]
 Ingesting quandl
[2023-06-18T23:17:24+0800-INFO][zipline.data.bundles.quandl]
 Downloading WIKI metadata.
Downloading WIKI Prices table from Quandl  [####################################]  100%
[2023-06-18T23:18:15+0800-INFO][zipline.data.bundles.quandl]
 Parsing raw data.
[2023-06-18T23:18:34+0800-INFO][zipline.data.bundles.quandl]
 Generating asset metadata.
Traceback (most recent call last):
  File "C:\Users\kenne\miniconda3\envs\zipline\Scripts\zipline-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\zipline\__main__.py", line 397, in ingest
    bundles_module.ingest(
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\zipline\data\bundles\core.py", line 445, in ingest
    bundle.ingest(
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\zipline\data\bundles\quandl.py", line 187, in quandl_bundle
    asset_metadata = gen_asset_metadata(raw_data[["symbol", "date"]], show_progress)
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\zipline\data\bundles\quandl.py", line 108, in gen_asset_metadata
    data["start_date"] = data.date.amin
  File "C:\Users\kenne\miniconda3\envs\zipline\lib\site-packages\pandas\core\generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'amin'. Did you mean: 'min'?

I'm using python 3.10.11, numpy 1.25.0, pandas 1.5.3 and conda 23.5.0.

Thanks,
Ken

**Comment by MBounouar** [comment]
Downgrading numpy to 1.23.5 should fix the issue

**Comment by ktan636** [comment]
Thanks @MBounouar. That worked!

**Comment by stefan-jansen** [comment]
Alternatively, retry with the latest, just released version.
