### ISSUE TITLE
Single Stocks Analysis Example doesn't work for SPY

### ISSUE THREAD

**Issue by AnilG3** [stefan-jansen/zipline-reloaded#25]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: MacOS Catalina 10.15.7
* Python Version: 3.8.10
* How did you install Zipline: conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

```
import pyfolio as pf
#Fetch the daily returns for a stock
stock_rets = pf.utils.get_symbol_rets('SPY')
```

* What did you expect to happen?

A dataframe of date and daily returns for SPY

* What happened instead?

Error message
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/site-packages/yfinance/multi.py", line 179, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/site-packages/yfinance/base.py", line 123, in history
    _time.strptime(str(start), '%Y-%m-%d')))
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/opt/anaconda3/envs/zipreload/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1/1/1970' does not match format '%Y-%m-%d'

```
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Write the code listed above or see https://github.com/quantopian/pyfolio/blob/master/pyfolio/examples/single_stock_example.ipynb
2. Retrieve daily returns for SPY
3. See error
...

## What steps have you taken to resolve this already?

This issue only happens with SPY, other tickers such QQQ, VOO work with no problem. The issue appears to be parsing of date in data received through yfinance package.

...

# Anything else?

It is my first time submitting an issue, not sure if I submitted the report correctly.
...

Sincerely,
Anil

**Comment by MBounouar** [comment]
This is not really an issue with zipline but pyfolio/yfinance maybe it would be better to open the issue there?

**Comment by stefan-jansen** [comment]
Indeed a pyfolio issue. Please open an issue [there](https://github.com/stefan-jansen/pyfolio-reloaded.
