### ISSUE TITLE
Not able to run zipline-bundle

### ISSUE THREAD

**Issue by arshpreetsingh** [stefan-jansen/zipline-reloaded#54]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)

Linux ubuntu-4gb-nbg1-1 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: `$ python --version`
Python 3.8.11

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
(zipline-38-pip) arsh@ubuntu-4gb-nbg1-1:~/zipline-reloaded$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'64

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
conda and pip both

* Python packages: `$ pip freeze` or `$ conda list`

# packages in environment at /home/arsh/anaconda3/envs/zipline-38-pip:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alembic                   1.7.3              pyhd8ed1ab_0    conda-forge
bcolz-zipline             1.2.4            py38hef53783_0    ml4t
bottleneck                1.3.2            py38h5c078b8_3    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.6                    pypi_0    pypi
click                     8.0.1            py38h578d9bd_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
cython                    0.29.24                  pypi_0    pypi
decorator                 4.4.2                      py_0    conda-forge
empyrical-reloaded        0.5.8                    py38_0    ml4t
greenlet                  1.1.1                    pypi_0    pypi
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      3.2                      pypi_0    pypi
importlib-metadata        4.8.1            py38h578d9bd_0    conda-forge
importlib_resources       5.2.2              pyhd8ed1ab_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
iso3166                   2.0.1              pyhd8ed1ab_0    conda-forge
iso4217                   1.6.20180829               py_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            11.2.0               h69a702a_8    conda-forge
libgfortran5              11.2.0               h5c6108e_8    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.7            py38h497a2fe_0    conda-forge
lxml                      4.6.3            py38hf1fe3a4_0    conda-forge
mako                      1.1.5              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
multipledispatch          0.6.0                    pypi_0    pypi
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  he6710b0_1  
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
numexpr                   2.7.3            py38h51da96c_0    conda-forge
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
pandas                    1.2.5                    pypi_0    pypi
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pip                       21.0.1           py38h06a4308_0  
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.11          h12debd9_0_cpython  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-interface          1.6.0                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
scipy                     1.7.1                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.23                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
statsmodels               0.12.2           py38h5c078b8_0    conda-forge
ta-lib                    0.4.19           py38hfeaa757_0    ml4t
tables                    3.6.1                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0    conda-forge
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yfinance                  0.1.63                     py_0    ml4t
zipline-reloaded          2.0.0.post1+36.g5e2fc85e          pypi_0    pypi
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h7b6447c_3  

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I am trying to ingest data but at initial step I am getting following error. 
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Traceback (most recent call last):
  File "/home/arsh/anaconda3/envs/zipline-38/bin/zipline", line 7, in <module>
    from zipline.__main__ import main
  File "/home/arsh/anaconda3/envs/zipline-38/lib/python3.8/site-packages/zipline/__init__.py", line 21, in <module>
    from trading_calendars import get_calendar
  File "/home/arsh/anaconda3/envs/zipline-38/lib/python3.8/site-packages/trading_calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/home/arsh/anaconda3/envs/zipline-38/lib/python3.8/site-packages/trading_calendars/trading_calendar.py", line 33, in <module>
    from .calendar_helpers import (
  File "/home/arsh/anaconda3/envs/zipline-38/lib/python3.8/site-packages/trading_calendars/calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

## What steps have you taken to resolve this already?

Sincerely,
`$ whoami`

**Comment by stefan-jansen** [comment]
Most likely addressed by #57 - please feel free to reopen if this issues persists.

**Comment by taeyurl** [comment]
> Most likely addressed by #57 - please feel free to reopen if this issues persists.
Is #57 the solution to the following problem?
 File "C:\Users\MPOWER\miniconda3\envs\env_zipline\Scripts\zipline-script.py", line 6, in <module>
    from zipline.__main__ import main
  File "C:\Users\MPOWER\miniconda3\envs\env_zipline\lib\site-packages\zipline\__init__.py", line 21, in <module>
    from trading_calendars import get_calendar
  File "C:\Users\MPOWER\miniconda3\envs\env_zipline\lib\site-packages\trading_calendars\__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "C:\Users\MPOWER\miniconda3\envs\env_zipline\lib\site-packages\trading_calendars\trading_calendar.py", line 33, in <module>
    from .calendar_helpers import (
  File "C:\Users\MPOWER\miniconda3\envs\env_zipline\lib\site-packages\trading_calendars\calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

**Comment by taeyurl** [comment]
I'm currently at the very basic stage which is to check that zipline was installed correctly by executing command
zipline run --help
install using mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded=2.0.0.post1
python 3.9

**Comment by arshpreetsingh** [comment]
I ended up forking and making some changes. 
https://github.com/arshpreetsingh/zipline-reloaded
