### ISSUE TITLE
ValueError: could not convert string to Timestamp  ( when i run "zipline bundles")

### ISSUE THREAD

**Issue by threehappy** [stefan-jansen/zipline-reloaded#95]
(base) C:\Users\Administrator>zipline ingest -b quandl
.......
(base) C:\Users\Administrator>zipline bundles
csvdir <no ingestions>
forex-csvdir-bundle <no ingestions>
Traceback (most recent call last):
  File "pandas\_libs\tslibs\conversion.pyx", line 648, in pandas._libs.tslibs.conversion._convert_str_to_tsobject
  File "pandas\_libs\tslibs\parsing.pyx", line 257, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "F:\Python\Anaconda3\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "F:\Python\Anaconda3\lib\site-packages\dateutil\parser\_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: SPY_benchmark.csv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Python\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Python\Anaconda3\Scripts\zipline.exe\__main__.py", line 7, in <module>
  File "F:\Python\Anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "F:\Python\Anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "F:\Python\Anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\Python\Anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\Python\Anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "F:\Python\Anaconda3\lib\site-packages\zipline\__main__.py", line 447, in bundles
    ingestions = list(map(str, bundles_module.ingestions_for_bundle(bundle)))
  File "F:\Python\Anaconda3\lib\site-packages\zipline\data\bundles\core.py", line 125, in ingestions_for_bundle
    return sorted(
  File "F:\Python\Anaconda3\lib\site-packages\zipline\data\bundles\core.py", line 127, in <genexpr>
    from_bundle_ingest_dirname(ing)
  File "F:\Python\Anaconda3\lib\site-packages\zipline\data\bundles\core.py", line 121, in from_bundle_ingest_dirname
    return pd.Timestamp(cs.replace(";", ":"))
  File "pandas\_libs\tslibs\timestamps.pyx", line 1332, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas\_libs\tslibs\conversion.pyx", line 407, in pandas._libs.tslibs.conversion.convert_to_tsobject
  File "pandas\_libs\tslibs\conversion.pyx", line 651, in pandas._libs.tslibs.conversion._convert_str_to_tsobject
ValueError: could not convert string to Timestamp

"zipline ingest -b quandl"    ok
but "zipline bundles" meet error:  ValueError: could not convert string to Timestamp

**Comment by garyfritzz** [comment]
I just encountered the same error on a fresh install in a new env.

**Comment by stefan-jansen** [comment]
Sorry for the late reply. We'd need more information so we can replicate this issue; looks like you have other bundles install already?

**Comment by jasonstrimpel** [comment]
@threehappy can you paste an image of the directory with your bundles?

**Comment by stefan-jansen** [comment]
Closing for lack of activity, please feel free to reopen if the issue persists and there is more info on how to address it.
