### ISSUE TITLE
Zipline ingest issue

### ISSUE THREAD

**Issue by Yashaswi07** [stefan-jansen/zipline-reloaded#99]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
[Zipline related screenshot.docx](https://github.com/quantopian/zipline/files/8500981/Zipline.related.screenshot.docx)

<details>

* Operating System: (Windows 10  Home)
* Python Version: `3.9.2`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: conda install -c ml4t zipline-reloaded
* Python packages: Please refer to the attachment

</details>

I have provided the details of the issue in the attahced file.

# Description of Issue
Unable to ingest data from quandl after executing the followng command:

zipline ingest -b quandl

* What did you expect to happen?
  I expected the zipline bundle to be locally deployed.
* What happened instead?
 The zipline bundle does not have any data and the exception is provided in th attachment.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.  zipline ingest -b quandl
2.  error stacktrace is triggered an captured in the attached file.

...

## What steps have you taken to resolve this already?
Haven't got any solution yet to incorporate.

...

# Anything else?

...

Sincerely,
Yashaswi

**Comment by johnjednorski** [comment]
I didn't download your attachment, but I assume I've run into the same error: 

`zipline ingest -b quandl
[2022-07-03 02:17:17.657496] INFO: zipline.data.bundles.core: Ingesting quandl.
[2022-07-03 02:17:17.657636] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
Downloading WIKI Prices table from Quandl  [####################################]  100%
[2022-07-03 02:17:35.497319] INFO: zipline.data.bundles.quandl: Parsing raw data.
[2022-07-03 02:17:57.562394] INFO: zipline.data.bundles.quandl: Generating asset metadata.
Merging daily equity files:  [--#---------------------------------]  1731$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/bcolz_daily_bars.py:366: UserWarning: Ignoring 1 values because they are out of bounds for uint32:             open  high   low  close        volume  ex_dividend  split_ratio
2011-04-11  1.79  1.84  1.55    1.7  6.674913e+09          0.0          1.0
  winsorise_uint32(raw_data, invalid_data_behavior, "volume", *OHLC)
Merging daily equity files:  [####################################]
[2022-07-03 02:20:45.564694] INFO: zipline.data.bundles.quandl: Parsing split data.
[2022-07-03 02:20:45.729681] INFO: zipline.data.bundles.quandl: Parsing dividend data.
Traceback (most recent call last):
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/construction.py", line 568, in _try_cast
    subarr = construct_1d_ndarray_preserving_na(subarr, dtype, copy=copy)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1625, in construct_1d_ndarray_preserving_na
    subarr = np.array(values, dtype=dtype, copy=copy)
ValueError: invalid __array_struct__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$MY_PATH/.venv/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "$MY_PATH/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "$MY_PATH/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/bundles/core.py", line 445, in ingest
    bundle.ingest(
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/bundles/quandl.py", line 207, in quandl_bundle
    adjustment_writer.write(
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/adjustments.py", line 691, in write
    self.write_frame("mergers", mergers)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/adjustments.py", line 444, in write_frame
    return self._write(
  File "$MY_PATH/.venv/lib/python3.9/site-packages/zipline/data/adjustments.py", line 393, in _write
    frame = pd.DataFrame(expected_dtypes, index=[])
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 83, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 351, in _homogenize
    val = sanitize_array(
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/construction.py", line 463, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "$MY_PATH/.venv/lib/python3.9/site-packages/pandas/core/construction.py", line 576, in _try_cast
    subarr = np.array(arr, dtype=object, copy=copy)
ValueError: invalid __array_struct__`

**Comment by stefan-jansen** [comment]
Should be fixed by latest updates, feel free to reopen if issue persists.
